### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by THEBEST1278** [math-gizmos/calculator#4]
when i click on the link i get directed to a black screen

**Comment by 3kh0** [comment]
> when i click on the link i get directed to a black screen

Play the game here: https://3kh0.github.io/projects/idle-breakout

**Comment by THEBEST1278** [comment]
link blocked by my district :(

**Comment by 3kh0** [comment]
> link blocked by my district :(

https://3kh0.netlify.app/
